test: &default

  # Credentials for REST APIs
  client_id: ASdd7WLrwOTqNIqVB0jx3H90vExstA2-f0QksseLLpKYJwgYFIhZDlfRbjcbdpuGWWR1hUoBdxbWXZgV
  client_secret: EPr-LzNJGEEmcWnr7xvipDKlmjEIKL13GqxfVpkc5-c649TyBQocnXISyExo1hd6k24n1cy3rurfHKgO

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: skakpovi-facilitator_api1.gmail.com
  password: M9A7D4ANEK8MVVRE
  signature: A8QLgfW-DLE4p1JJ5a.ibVVd1RtAAUBQSKIp9Wb0EmGMQLpdD8XP0TGV
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

  # verbose_logging: true

development:
  <<: *default

production:
  <<: *default
  mode: live
